[IV-24-25] Objetivo 2
juanmaaf/MoneyController pull request #11
Opened 2024-10-23 17:03 UTC by MatteoImbrosciano

## Sobre la estructura del repositorio

- [ ] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y disposición de los mismos?
- [ ] ¿He mirado tanto reglas generales (para cualquier repo) como reglas específicas para el lenguaje con el que se está trabajando?

## Sobre el planteamiento

- [ ] ¿Se han planteado una serie de issues, asignados a las historias de usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e identifiquen las diferentes partes del problema?
- [ ] ¿Los issues representan un problema, y no una tarea?

## Sobre el análisis del problema

- [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo que se ha creado?
- [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor, una entidad o un agregado?
- [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo objeto valor que no dependa de ningún otro (y que sea la base de muchos otros)?

## Sobre el código

- [ ] ¿Todos los mensajes de commit explican el cambio, y no se limitan a repetir el nombre del fichero que se ha cambiado?
- [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
- [ ] ¿Se ha hecho una revisión real del código para comprobar que todos los atributos y funciones creadas están respaldadas por una HU?
- [ ] ¿Todos los issues creados están relacionados con a una HU?
- [ ] ¿Ha asignado el propietario/la propietaria del repositorio todos los issues planteados al milestone correspondiente?
- [ ] ¿Todos los cambios en el código están asignados a un issue al que se referencia en un commit?
- [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
- [ ] ¿Es el milestone sobre el que estoy trabajando un producto mínimamente viable? ¿O tengo que solicitar al product manager que precise de qué producto se trata?
- [ ] ¿Se ha comprobado que el código entregado sea sintácticamente correcto?

## Lista de comprobación para el propietario/a del repositorio

- [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y evidencian comprensión de las historias de usuario? Si no es así, es mejor que se le transmita antes de que empiece a crear cualquier código erróneo.
- [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido su lista de comprobación?
- [ ] ¿El código creado es una modelización válida de las historias de usuario creadas por ti, y te sirve como base para programar la lógica de negocio?
- [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de programación que hayáis consensuado, tanto en identificadores, como nombres de ficheros, como disposición de los diferentes ficheros en el repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y aportan código para resolver el problema planteado en el mismo?
- [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo ha hecho y documentado en el repositorio?
- [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone correspondiente, que será el primero?
- [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en el objetivo 4 para poder programar la lógica de negocio?
- [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-10-24 08:52 UTC, MatteoImbrosciano commented
Hola @juanmaaf, podrías asociar el milestone "M0" con el milestone aquí en el PL

2024-10-25 10:37 UTC, MatteoImbrosciano commented
@juanmaaf puedes revisar

2024-10-25 10:53 UTC, juanmaaf reviewed
Basándome en la lista de comprobación y en los errores que me han comentado en mi desarrollo, he hecho una serie de comentarios. Te recomendaría además incluir algún tipo de documentación.

2024-10-25 10:53 UTC, juanmaaf commented on main.py
> +from src.gasto import Gasto
En el guión del objetivo no se especifica que haya que crear un archivo main. No es necesario realizar comprobaciones del código, ya que únicamente se pide el modelo de las entidades. Te recomendaría eliminarlo.

2024-10-25 10:53 UTC, juanmaaf commented on iv.yaml
> +lenguaje: python
Considera cambiar el nombre del directorio src por, por ejemplo, money_controller, ya que en Python no es correcto emplear el nombre src. Puedes ver el PR del repositorio en el que estoy trabajando y me han indicado el mismo error. Además, debes crear un archivo pyproject.toml, necesario en los proyectos de Python.

2024-10-25 10:53 UTC, juanmaaf commented on src/presupuesto.py
> +        self.monto_total = monto_total
Te recomiendaría considerar ingresos en el Presupuesto, ya que si únicamente se añaden los gastos, el saldo será siempre negativo.

2024-10-25 11:28 UTC, MatteoImbrosciano commented
@juanmaaf  Hice los cambios recomendados y agregué el archivo "pyproject.toml"

2024-10-27 19:18 UTC, MatteoImbrosciano commented
@juanmaaf puedes revisar

2024-10-28 17:34 UTC, juanmaaf reviewed
Perdona, pero no puedo revisar 1791 archivos. Añade al .gitignore lo que veas correspondiente para que no se añadan al repositorio archivos innecesarios.

2024-10-28 18:03 UTC, MatteoImbrosciano commented
@juanmaaf Eliminé los archivos inútiles para que puedas revisarlos.

2024-10-29 16:12 UTC, juanmaaf requested changes
Estás cerca, pero tienes que tener en cuenta qué es un PMV. Únicamente debes modelar las entidades, sin métodos que no sean necesarios. Además, considera incluir al .gitignore los archivos del directorio __pycache__ para que no se llene el repositorio de archivos.

2024-10-29 16:12 UTC, juanmaaf commented on money_controller/gasto.py
> +    def es_fijo(self):
Únicamente se pide modelizar las entidades. El PMV no pide que se implementen métodos. Únicamente se podrán implementar métodos de validación que sean necesarios.

2024-10-30 14:47 UTC, MatteoImbrosciano commented
@juanmaaf  Cambié las cosas que me dijiste. Espero que todo vaya bien. 
Espero el tuyo feedback para una posible modificación.

2024-10-31 08:37 UTC, MatteoImbrosciano commented on money_controller/gasto.py
> +    def es_fijo(self):
lo resolví para acqui:" https://github.com/juanmaaf/MoneyController/pull/11/commits/ac05be54e7ea54d4a60ccb81ca63bf072e53aaad"

2024-11-04 15:10 UTC, juanmaaf approved these changes
Perdona por la espera para realizar la revisión. Muchas gracias por tu trabajo. Creo que has definido un buen PMV. Seré capaz de continuar el desarrollo del próximo PMV en el siguiente Milestone. No obstante, veo que has realizado algún commit que no se relaciona con ningún issue. Queda pendiente la revisión de @JJ.

2024-11-04 16:31 UTC, JJ requested changes
@juanmaaf el primero que tiene que ver si puede trabajar con esto eres tú. ¿Crees que lo hecho es un modelo suficiente y que por tanto cumple el criterio de validez del milestone 0?

2024-11-04 16:31 UTC, JJ commented on .gitignore
> +<<<<<<< HEAD
Aquí hay una marca de conflicto. Por favor eliminadla.

2024-11-04 16:31 UTC, JJ commented on .gitignore
> +>>>>>>> e70bf4b683559a8722dc67bcf02bb4fbb2b1f94f
Y aquí. Aprended a reconocer las marcas de conflicto de fusión y a solucionar este tipo de problemas.

2024-11-04 16:31 UTC, JJ commented on money_controller/gasto.py
> +#¿Cómo podemos categorizar los gastos en fijos y variables?
la referencia a la historia de usuario se hace en un issue, y al issue en el commit.

2024-11-04 16:31 UTC, JJ commented on money_controller/gasto.py
> +    descripcion: str  # La descrizione della spesa
No es buena práctica usar comentarios de esta forma. Se deben usar docstrings que se puedan entender por parte de IDEs como VScode

2024-11-04 16:31 UTC, JJ commented on money_controller/gasto.py
> +    fijo: bool = True # True per spese fisse, False per variabili
¿hay alguna diferencia entre los gastos fijos y variables aparte del hecho de ser fijos? ¿Seguro que simplemente poner `fijo` ya es suficiente? ¿Esa es la solución a #8?

2024-11-04 18:13 UTC, JJ commented
@MatteoImbrosciano 
1. @juanmaaf dovrà fare un'altra revisione prima che io acceti oppure no.
2. Nessun commit fa un "cancellato"-collegamento a nessun issue. Se non si lavora con gli issue, non si fa niente.

2024-11-04 18:16 UTC, MatteoImbrosciano commented
Si el valor booleano no satisface la solicitud, puedo crear una cadena estándar que tomará dos valores, a saber, "fijo" y "variable". @JJ  @juanmaaf

2024-11-04 18:30 UTC, JJ commented
> Si el valor booleano no satisface la solicitud, puedo crear una cadena estándar que tomará dos valores, a saber, "fijo" y "variable". @JJ @juanmaaf

É lo stesso. Devi ricercare il problema, non dargli nomi alle cose.

2024-11-07 08:01 UTC, MatteoImbrosciano commented
@JJ puede revisar

2024-11-07 10:42 UTC, JJ requested changes
Para empezar, elimina los ficheros que no corresponden al repo y trata de seguir buenas prácticas en el uso de git. A continuación, @juanmaaf debería revisarlo y aprobarlo antes de pasar a otra revisión.

2024-11-07 10:42 UTC, JJ commented on iv.yaml
> +  - money_controller/categoriaGasto.py
De todos esos ficheros, ¿cuál contiene una entidad en el sentido de domain driven design?

2024-11-07 10:42 UTC, JJ commented on money_controller/__pycache__/gasto.cpython-310.pyc
Agh, añadido pycache al repositorio.

NUNCA HAGÁIS GIT ADD .

2024-11-07 11:01 UTC, juanmaaf reviewed
Resuelve el comentario del profesor respecto al fichero iv.yaml. El resto lo veo bien.

2024-11-07 11:05 UTC, MatteoImbrosciano commented
Arreglé el fichero iv.yaml. @JJ @juanmaaf

2024-11-07 11:20 UTC, JJ approved these changes
Si a @juanmaaf le sirve, no tengo más que añadir.

2024-11-07 11:20 UTC, JJ commented on iv.yaml
> +  - money_controller/gasto.py
Questo in YAML è un array con uno singolo elemento. Ciò che si cerca è una semplice coppia chiave/valore. Non è così importante adesso, ma bisogna capire come va YAML.

2024-11-07 12:21 UTC, merged