[IV-24-25] Objetivo 4
juanmaaf/MoneyController pull request #17
Opened 2024-12-11 11:05 UTC by juanmaaf

* [x]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [x]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [x]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [x]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [x] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [x] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [x] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [x] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [x]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [x]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [x] ¿Se han testeado también las excepciones?

2024-12-16 08:34 UTC, antoniorr02 reviewed
Buenos días, se me ha asignado revisar tu PR, en general está bastante bien y no he encontrado nada muy destacable.

Por otro lado a parte del comentario que te pongo a continuación sobre uno de los criterios, has dejado una de las casillas en el cuerpo del PR sin marcar como completada.

2024-12-16 08:34 UTC, antoniorr02 commented on docs/biblioteca_aserciones.md
> +- Se considerará que la herramienta incluya una mayor variedad de aserciones.
No acabo de entender este criterio, de hecho luego ni lo utilizas a la hora de la elección.

2024-12-16 14:28 UTC, juanbarearojo reviewed
Se me ha asignado revisar tu pr. En general veo que has realizado bastante trabajo pero te recomiendo que tengas cuidado con el uso de número mágicos ya que disminuyen las legibilidad del código. El código está pensado para ser leído y a lo mejor para ser ejecutado.

2024-12-16 14:28 UTC, juanbarearojo commented on tests/test_gasto.py
> +        self.assertEqual(presupuesto.monto_total, 1000 + 500 - 226.67 - 50)
¿Has considerado el uso de constantes? Lo digo porque puede ser confuso ver test con valores mágicos

2024-12-16 14:28 UTC, juanbarearojo commented on tests/test_gasto.py
> +        procesar_gasto(presupuesto, gastos_vistos, "Alquiler", "Vivienda", 226.67, datetime(2024, 1, 1))
Veo que 226.67 se repite bastante por eso lo decía. De esta forma podemos hacer que lo test sean más legibles.

2024-12-16 16:09 UTC, hossam1522 reviewed
Realmente, aparte del pequeño comentario que he dejado y lo comentado por los compañeros, en general lo veo bastante correcto.

2024-12-16 16:09 UTC, hossam1522 commented on docs/biblioteca_aserciones.md
> +- Se considerará que la herramienta ofrezca una amplia gama de opciones para realizar diferentes tipos de aserciones.
Pregunto, ¿realmente por qué te hacen falta diferentes tipos?

2024-12-16 16:50 UTC, juanmaaf commented
En primer lugar, muchas gracias por vuestros comentarios. Respecto al comentario de @juanbarearojo, he seguido las buenas prácticas estableciendo variables en el principio del archivo, dejando de usar números mágicos en los test. Respecto al comentario de @hossam1522 , me ha hecho pensar tu pregunta y he llegado a la conclusión de que reduce la deuda técnica del proyecto tener una herramienta que te ahorre la implementación de la lógica de la aserción, por lo que he hecho cambios en la correspondiente línea indicándolo. Revisión, por favor. @hossam1522 @juanbarearojo

2024-12-16 21:07 UTC, antoniorr02 approved these changes
Buenas, viendo los cambios que has hecho segun las indicaciones de @juanbarearojo  y @hossam1522 , en principio tienes mi aprobado, ya que si no se me escapa nada no veo motivo para no dartelo.

2024-12-17 08:40 UTC, juanbarearojo approved these changes

2024-12-18 11:28 UTC, hossam1522 approved these changes
Por mi parte, también está aprobado.

2024-12-19 11:28 UTC, juanmaaf commented
Revisión @JJ

2024-12-19 11:49 UTC, JJ reviewed
Te falta el comando que sirve para elegir los tests.

2024-12-19 11:49 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerarán las herramientas que tengan soporte activo. Podemos verificarlo viendo en las páginas de [Snyk Advisor](https://snyk.io/advisor/) y [PyPi](https://pypi.org/) si las últimas versione
Esto ¿está incluido en la puntuación de arriba o no? ¿Si está incluido, por qué no disgregas los diferentes criterios?
Recientes, ¿cuanto? Tendrás que hacerlo con respecto a algún criterio objetivo, como la frecuencia de nuevas actualizaciones de Python. Tipo: la última salió "2 versiones de Python atrás" o algo así.

2024-12-19 11:49 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerará que la herramienta ofrezca una amplia gama de opciones para realizar diferentes tipos de aserciones. Esto evitará deuda técnica innecesaria en el futuro, permitiendo escribir pruebas
Si ya hemos hablado de aserciones tipo BDD y los otros tipos y se puede ver de forma objetiva, ¿por qué no usáis eso?
También deberías hablar de tipos de aserciones específicos, por ejemplo, ¿se pueden testear excepciones?

2024-12-19 11:49 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerará si existe un estándar en el lenguaje de programación.
No va a existir estándares sobre esto. Si acaso, *bibliotecas* incluidas en el propio lenguaje.

2024-12-19 12:35 UTC, juanmaaf commented
Revisión @JJ

2024-12-19 13:18 UTC, JJ reviewed
- Los issues tienen que ser un problema
- El código desarrollado tiene que resolver ese problema
- El test tiene que probar que el problema se haya resuelto.

2024-12-19 13:18 UTC, JJ commented on docs/test_runner.md
> +Finalmente, elegidos biblioteca de aserciones y test runner necesitamos la elección final del comando que ejecutará estos test. Tenemos que evaluar las distintas Herramientas CLI disponibles para eje
No has puesto ningún criterio.

2024-12-19 13:18 UTC, JJ commented on money_controller/gasto.py
> +    fecha: datetime
¿Por qué has borrado el docstring?

2024-12-19 13:18 UTC, JJ commented on money_controller/gasto.py
> +    importe: float
¿por qué has cambiado monto por importe?

2024-12-19 13:18 UTC, JJ commented on money_controller/gasto.py
> +    concepto: str
¿por qué has cambiado el nombre de las variables?

2024-12-23 14:50 UTC, juanmaaf commented
Revisión @JJ

2024-12-30 08:13 UTC, JJ commented
Ya dijimos desde el objetivo 2º que los commits no debían describir lo que hacía el nuevo código, sino explicar el por qué. Tampoco siguen la buena práctica de tener 50 caracteres en la primera línea, por lo que aparecen partidos.
Saber crear buenos mensajes de commit es esencial para hacer más eficiente la revisión, porque permite explicar qué es lo que se ha hecho.

2024-12-30 08:16 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerarán las herramientas que tengan actualizaciones recientes valorando este criterio en función del número de actualizaciones de Python que han pasado hasta que la herramienta se haya actu
No entiendo este criterio. Si en vez de "hasta" hubieras escrito "desde", sería un poco más entendible, pero aún así parece simplemente una excusa para elegir una en vez de otra.

2024-12-30 08:17 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerará que la herramienta ofrezca una amplia gama de opciones para realizar diferentes tipos de aserciones, como los tipos (igualdad, veracidad, mayor/menor, etc.), aserciones específicas d
¿"Amplitud" se puede medir objetivamente?

2024-12-30 08:17 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerará si existe una biblioteca de aserciones en el lenguaje de programación. En este caso, que esté en la biblioteca de Python.
¿Qué es "en"? Procura hablar con precisión, por favor.

2024-12-30 08:18 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerarán las herramientas que tengan actualizaciones recientes valorando este criterio en función del número de actualizaciones de Python que han pasado hasta que la herramienta se haya actu
OK, ya lo entiendo mirando como la evalúas. ¿Estás hablando de "versiones" en vez de actualizaciones? Versiones, además, ¿de qué tipo? ¿*Minor*? ¿*Patch*?

2024-12-30 08:19 UTC, JJ commented on docs/gastos.csv
> +2024-02-16,Bizum Recibido,Transferencias,18.7,Ingreso
¿Como sabes qué gasto es si solo pone Bizum Recibido o Enviado?

2024-12-30 08:20 UTC, JJ commented on docs/herramientas_cli.md
> +    Nose2 es una extensión de Unittest e incluye características que lo hacen más flexible y avanzado. No obstante, si vemos su página de Snyk Advisor, a pesar de tener una puntuación media-alta y de
¿Extensión de UnitTest? ¿Por qué es una extensión?

2024-12-30 08:20 UTC, JJ commented on docs/herramientas_cli.md
> +# Conclusión
¿Alguno de los que has descrito en otros apartados tiene línea de órdenes también para ejecutar?

2024-12-30 08:21 UTC, JJ commented on docs/biblioteca_aserciones.md
> +# Conclusión
¿Seguro que no mencionan alguno más?

2024-12-30 08:26 UTC, JJ commented on money_controller/gasto.py
>      Atributos:
Esto se ha añadido en el commit https://github.com/juanmaaf/MoneyController/commit/b74ff1c4b179e87e1d645b44930ac61e37306365
Para empezar, si quieres cerrar tienes que poner closes delante de cada issue. Pero para seguir, si pones esto y cambias retornos de carro o lo que sea va a aparecer como que se ha añadido por esto. Deberías intentar cerrar issues cambiando documentación, por ejemplo, para que no afecte al código.

2024-12-30 11:22 UTC, juanmaaf commented on money_controller/gasto.py
>      Atributos:
Para empezar de 0, hice referencia a los 3 issues incorrectos #20, #21 y #22 eliminando todo el contenido y dejando el código resultado del objetivo 2. A partir de ahí, empecé de 0.

2024-12-30 11:25 UTC, juanmaaf commented on docs/gastos.csv
> +2024-02-16,Bizum Recibido,Transferencias,18.7,Ingreso
Es lo que genera el banco. Un bizum enviado refleja un Gasto al ser una salida de dinero. Un bizum recibido refleja un Ingreso al ser una entrada. Lo incluiré en el Readme.

2024-12-30 11:46 UTC, juanmaaf commented
He asignado los issues al correspondiente Milestone y mencionado la Historia de Usuario. Además, he reformulado los criterios buscando que sean objetivos. Revisión, por favor. @JJ

2024-12-31 07:53 UTC, JJ requested changes
Puedes tomarte tu tiempo corrigiendo (si es posible, *de verdad*) lo que he comentado *en la revisión anterior*.

2024-12-31 07:53 UTC, JJ commented on docs/biblioteca_aserciones.md
> +a basada en cuatro distintos criterios (Security, Popularity, Maintenance y Community). Se considerará esta puntuación como el nivel de salud de la herramienta.
Esta división de "est" y "a" en dos líneas no se debe en absoluto a que lo hayas copiado y pegado de alguna IA generativa. En todo caso, para animarte a que no cometas estos errores tecleando lo que tú solo has pensado, dejo de corregir aquí y penalizo con varios días de retraso en la siguiente corrección, como se ha avisado en el grupo de Telegram de clase y los errores frecuentes.

2024-12-31 07:53 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerarán las herramientas que tengan una alta puntuación en [Snyk Advisor](https://snyk.io/advisor/). Esta puntuación est
Estamos yendo otra vez por el mismo camino, y sabes donde acaba este camino. Estás
1. Reescribiendo los criterios completos, en vez de hacer correcciones puntuales en lo que se te ha comentado.
2. Cambiando palabras por otras que son similares e igualmente malas persiguiendo únicamente que se "elimine" el comentario. ¿De veras que crees que cambiar "buena" por "alta" es una mejora?

2024-12-31 10:15 UTC, juanmaaf commented on docs/biblioteca_aserciones.md
> +- Se considerarán las herramientas que tengan una alta puntuación en [Snyk Advisor](https://snyk.io/advisor/). Esta puntuación est
Cambié buena por alta pensando que el criterio se entendería objetivo, dado que la puntuación es entre 0 y 100. Además, explico los distintos criterios que emplea Snyk para obtener y mostrar esta puntuación. Las herramientas se pueden comparar de forma objetiva mediante este criterio, gracias a Snyk, de forma general y de forma específica observando la valoración para cada uno de los cuatro criterios. No entiendo por qué no son válidos estos criterios. Ya me han revisado y aceptado compañeros con criterios similares.

2024-12-31 10:30 UTC, juanmaaf commented on docs/biblioteca_aserciones.md
> +a basada en cuatro distintos criterios (Security, Popularity, Maintenance y Community). Se considerará esta puntuación como el nivel de salud de la herramienta.
No he usado IA para la formulación de los criterios. De hecho, para este criterio concretamente he observado cómo lo han formulado mis compañeros y lo he tratado de escribir de la forma más objetiva posible, dado que hasta ahora lo ha entendido como subjetivo. He cometido el error de saltar línea un carácter antes. Doble error el no haber leído todo de nuevo. Estoy lejos de la superación del objetivo, porque aún no ha llegado a revisar el código.

2025-01-07 10:42 UTC, JJ requested changes
Encontrados ya 3 comentarios que no has resuelto, dejo de revisar. Por favor, mira esos comentarios y corrige lo que estimes conveniente. Cuando lo hagas, solicita revisión de nuevo.

2025-01-07 10:42 UTC, JJ commented on docs/biblioteca_aserciones.md
> +# Conclusión
No has resuelto este comentario.

2025-01-07 10:42 UTC, JJ commented on docs/gastos.csv
> +2024-02-16,Bizum Recibido,Transferencias,18.7,Ingreso
Este tampoco.

2025-01-07 10:42 UTC, JJ commented on docs/herramientas_cli.md
> +2. **Unittest (PyUnit)**:
¿Qué  herramienta CLI tiene esto?

2025-01-07 10:56 UTC, juanmaaf commented on docs/gastos.csv
> +2024-02-16,Bizum Recibido,Transferencias,18.7,Ingreso
Lo expliqué al final del README, indicando que como el problema del usuario es categorizar los gastos en fijos y variables, se considerará la Transferencia como gasto fijo en caso de ser recurrente. Descargué mi propio estado bancario para comprobar y sacar datos reales.

2025-01-07 10:58 UTC, juanmaaf commented on docs/gastos.csv
> +2024-02-16,Bizum Recibido,Transferencias,18.7,Ingreso
Si tanto problema dan los Bizum, consideraré eliminarlos o cambiar Bizum Enviado y Recibido por su Concepto asociado, formando parte de la categoría "Transferencias".

2025-01-07 11:15 UTC, JJ commented on docs/gastos.csv
> +2024-02-16,Bizum Recibido,Transferencias,18.7,Ingreso
(Poniendo cara de clipy). Um, parece que tienes un problema. ¿Habrá alguna herramienta en desarrollo ágil donde se pueden presentar los problemas de forma que sea fácil desarrollar código para solucionarlos?

2025-01-07 11:21 UTC, juanmaaf commented on docs/herramientas_cli.md
> +# Conclusión
Sí. Añadí más herramientas para resolver este Comentario.

2025-01-07 11:23 UTC, JJ commented on docs/herramientas_cli.md
> +# Conclusión
Pues no hace falta que te repita cómo tienes que resolverlo entonces, indicando en qué commit se ha hecho.

2025-01-07 11:25 UTC, juanmaaf commented on docs/herramientas_cli.md
> +2. **Unittest (PyUnit)**:
Resuelto en el último commit.

2025-01-07 11:28 UTC, juanmaaf commented on docs/biblioteca_aserciones.md
> +# Conclusión
Había puesto 6 herramientas. En el momento que realicé esta parte del objetivo no vi más. Revisaré de nuevo los foros.

2025-01-07 11:34 UTC, juanmaaf commented on docs/herramientas_cli.md
> +# Conclusión
Resuelto en #[6d70d10](https://github.com/juanmaaf/MoneyController/pull/17/commits/6d70d10901b3374715facdd040144937a9d898e7)

2025-01-07 11:35 UTC, juanmaaf commented on docs/herramientas_cli.md
> +# Conclusión
Ya he me he dado cuenta que Unittest no es Herramienta CLI. Está eliminado.

2025-01-07 11:53 UTC, juanmaaf commented on docs/biblioteca_aserciones.md
> +# Conclusión
Estoy viendo las distintas herramientas que se mencionan, pero no veo que se mencionen más bibliotecas de aserciones. 
- Ward: Herramienta inactiva. (https://github.com/darrenburns/ward)
- Hypothesis: No es una biblioteca de aserciones. Es una biblioteca para pruebas basada en propiedades. Genera pruebas de entrada para testear el código. No dispone de aserciones como Pytest, Unittest o el resto de herramientas. 
- Las herramientas para pruebas asíncronas creo que no entran en el desarrollo del proyecto de esta asignatura.

2025-01-07 11:54 UTC, juanmaaf commented on docs/biblioteca_aserciones.md
> +# Conclusión
No había mencionado Behave, que incluye aserciones tipo BDD. Lo incluiré.

2025-01-07 12:12 UTC, juanmaaf commented on docs/biblioteca_aserciones.md
> +# Conclusión
Añado herramienta en: [aa33225](https://github.com/juanmaaf/MoneyController/pull/17/commits/aa33225e2e7420d50e20565b6dad35ee558fb825)

2025-01-07 12:45 UTC, juanmaaf commented
He resuelto el error que tenía a través de un issue, justificando los cambios basándome en el problema. He tratado de resolver todos los comentarios. Revisión @JJ, por favor.

2025-01-08 07:37 UTC, JJ requested changes
Aparte de todos los errores de procedimiento, no estás implementando ninguna lógica de negocio más allá de decirle "este gasto es fijo, cámbialo de variable a fijo". Desde el objetivo 0 dijimos que *realmente* teníais que resolver un problema, no cambiar nombre a las cosas o almacenar y recuperar.
Si lo que quieres es concentrarte en calcular el presupuesto, puedes hacerlo. Si quieres crear un fichero de gastos más complejo que haya que procesar, también. Lo que no puedes es no resolver el problema simplemente diciendo "estos gastos son fijos"

Por otro lado, también tendrías que tener en cuenta si realmente estás usando para algo la "categoría". No me parece que aporte mucho a la lógica de negocio.

2025-01-08 07:37 UTC, JJ commented on money_controller/gasto.py
> +    fecha: datetime
A estas alturas deberías saber ya que no se cierra simplemente un comentario. Se resuelve *siempre* con un commit.

2025-01-08 07:37 UTC, JJ commented on docs/test_runner.md
> +- Se considerará que la herramienta tenga un sistema de fixtures y proporcione salidas detalladas.
De veras que a estas alturas tener que ver esto... ¿Has leído los errores frecuentes?

2025-01-08 07:37 UTC, JJ commented on money_controller/presupuesto.py
> +                raise ValueError("El archivo está vacío.")
¿Qué archivo está vacío?

2025-01-08 07:37 UTC, JJ commented on money_controller/presupuesto.py
> +                gasto.categoria=CategoriaGasto.FIJO
¿Qué estás haciendo aquí exactamente? ¿Por qué cambias la categoría de variable a fijo?

2025-01-08 07:37 UTC, JJ commented on money_controller/presupuesto.py
> +        gastos_vistos[clave_gasto] = True
De todas las formas de procesar un array, la peor es cambiarlo y poner un "flag" a "True". No sé muy bien qué estás haciendo aquí, porque "procesar" es una palabra genérica. Pero me da la impresión de que hace varias cosas: "Ver" o no los gastos, y también cambiar categoría de gastos.

2025-01-08 07:37 UTC, JJ commented on money_controller/presupuesto.py
> +            if gasto.descripcion == descripcion and gasto.monto == monto and gasto.categoria == CategoriaGasto.VARIABLE:
¿has oido hablar de la complejidad ciclomática? ¿Crees que un if dentro de un bucle dentro de un if es la mejor forma de hacer esto? ¿Has oído hablar de filtros y de "maps"?

2025-01-08 07:37 UTC, JJ commented on money_controller/presupuesto.py
> +    meta_ahorro: float = None
Esto lo has hecho "cerrando" el issue #23, que *es incorrecto* como dice en el [comentario](https://github.com/juanmaaf/MoneyController/issues/23#issuecomment-2565168497), al que no has respondido.

2025-01-08 07:37 UTC, JJ commented on money_controller/presupuesto.py
> +def procesar_datos(ruta_archivo):
¿Te parece que dos funciones que se llamen "procesar datos" y "procesar gastos" tengan una denominación adecuada?

2025-01-08 07:37 UTC, JJ commented on docs/gastos.csv
> +2024-01-01,Alquiler,Vivienda,226.67,Gasto
¿El usuario de #2 tiene que meter toda esta información? ¿Debe decidir si es Vivienda u Ocio? ¿Sabe qué categorías hay? ¿No debería ser un valor adicional de tu programa?

2025-01-08 07:37 UTC, JJ commented on docs/gastos.csv
> +Fecha,Concepto,Categoría,Importe,Tipo Movimiento
Para saber si es ingreso o gasto, ¿no sería suficiente si la cantidad es positiva o negativa?

2025-01-08 07:37 UTC, JJ commented on money_controller/presupuesto.py
> +        for gasto in presupuesto.gastos_variables:
Un mensaje de commit debe indicar claramente cómo se ha resuelto algo. Tratándose de la clave de tu lógica de negocio, cuales de los gastos son fijos y cuales no, decir "definit método para procesar los datos" deja algo que desear. El issue #21 tampoco ofrece ninguna pistas de las alternativas que se han planteado. Aparentemente se convierte en fijo si tiene una descripción y un monto determinado y es variable. Así que no entiendo nada de esta lógica de negocio. Es imposible saber si es correcta o no.

2025-01-08 07:37 UTC, JJ commented on test/test_gasto.py
> +from money_controller.presupuesto import leer_archivo_csv
¿las buenas prácticas de python dicen que hay que usar todas estas líneas para importar?

2025-01-08 07:37 UTC, JJ commented on test/test_gasto.py
> +            self.assertEqual(str(contexto.exception), f"El archivo {ruta_archivo} no existe")
¿Esto qué valor añade al cliente?

2025-01-08 07:37 UTC, JJ commented on test/test_gasto.py
> +    def test_leer_archivo_error(self):
Todos estos tests, ¿qué valor añaden al cliente?

2025-01-08 07:37 UTC, JJ commented on test/test_gasto.py
> +    def test_actualizar_monto_total(self):
¿Esto añade valor al cliente o simplemente prueba que Python sabe sumar?

2025-01-08 07:37 UTC, JJ commented on test/test_gasto.py
> +        procesar_gasto(presupuesto, gastos_vistos, "Alquiler", "Vivienda", ALQUILER_IMPORTE, FECHA_ALQUILER)
A ver si lo entiendo bien. ¿Le estás diciendo tú qué son los gastos fijos? ¿No se supone que es un valor que tendría que añadirse por parte de tu programa? ¿No quedamos que tenías que usar alguna heurística para saber qué gastos eran fijos?

2025-01-08 07:37 UTC, JJ commented on money_controller/presupuesto.py
> +                presupuesto.gastos_variables.remove(gasto)
¿Tienes que cambiar la categoría *y* cambiarlo de array?

2025-01-08 08:53 UTC, juanmaaf commented on docs/gastos.csv
> +Fecha,Concepto,Categoría,Importe,Tipo Movimiento
Al descargar el estado bancario lo muestra así, al menos el mío. Añade al final Ingreso/Gasto y muestra todos los importes positivos. Igualmente, lo consideraré.

2025-01-08 08:55 UTC, juanmaaf commented on docs/gastos.csv
> +2024-01-01,Alquiler,Vivienda,226.67,Gasto
Mi Banco categoriza los gastos en unas 9 categorías y lo muestra en el estado bancario. Igualmente lo consideraré y será valor adicional para mí programa.

2025-01-08 08:57 UTC, JJ commented on docs/gastos.csv
> +2024-01-01,Alquiler,Vivienda,226.67,Gasto
Todo eso tendrás que documentarlo, entonces, y validar esas categorías. En todo caso, si lo vas a usar en la lógica de negocio úsalo, si no ¿para qué quieres almacenarlo?

2025-01-08 09:00 UTC, juanmaaf commented on money_controller/presupuesto.py
> +    meta_ahorro: float = None
Reformulé el issue atendiendo al comentario. Formulaba una tarea y lo cambié a un problema.

2025-01-08 09:04 UTC, juanmaaf commented on money_controller/presupuesto.py
> +        for gasto in presupuesto.gastos_variables:
Se convierte en fijo la primera vez que se procesa un gasto. Por cada gasto, se usa como clave su concepto, categoría e importe. La clave de cada gasto procesado va al array gastos_vistos. Si se procesa un gasto cuya clave ya ha sido vista, se considerará variable al haber recurrencia. No se me ha ocurrido otra solución para resolver el problema, pero creo que crea valor.

2025-01-08 09:07 UTC, juanmaaf commented on money_controller/presupuesto.py
> +                gasto.categoria=CategoriaGasto.FIJO
Porque cuando se procesa un gasto ya visto, inicialmente habrá uno catalogado como Fijo que no lo es. Automáticamente se cambia ese gasto a Variable, por coherencia con los gastos con la misma clave (concepto, importe, categoría). Reformularé el issue y justificaré de mejor forma la lógica que aplico y trato de modelizar.

2025-01-08 09:10 UTC, juanmaaf commented on money_controller/presupuesto.py
> +                presupuesto.gastos_variables.remove(gasto)
Como categorizo los gastos en Variables cuando su clave (concepto, importe, categoría) aparece en el array gastos_vistos, el primer procesamiento de un gasto variable siempre va a ser como gasto fijo al desconocerse el resto de gastos. Los gastos se procesan uno a uno en serie. Cuando llega un gasto que se categoriza como Variable, tiene que convertir a Variable el primer gasto con esa clave que se categoriza como Fijo.

2025-01-08 09:10 UTC, juanmaaf commented on money_controller/presupuesto.py
> +def procesar_datos(ruta_archivo):
Lo consideraré.

2025-01-08 09:11 UTC, juanmaaf commented on money_controller/presupuesto.py
> +        gastos_vistos[clave_gasto] = True
Lo consideraré y trataré de separarlo por partes en ese caso.

2025-01-08 09:12 UTC, juanmaaf commented on test/test_gasto.py
> +            self.assertEqual(str(contexto.exception), f"El archivo {ruta_archivo} no existe")
Como en el guion dice que hay que testear las excepciones, planteé distintas posibilidades. Lo consideraré.

2025-01-08 09:12 UTC, JJ commented on money_controller/presupuesto.py
> +    meta_ahorro: float = None
Los issues sirven para expresar problemas y el código para resolver problemas. Si un issue es incorrecto y se ha desarrollado código usándolo, *los dos son incorrectos*, hay que crear un nuevo issue y nuevo código. Si no, puede dar lugar a confusión como la que está ocurriendo ahora mismo.

2025-01-08 09:15 UTC, JJ commented on test/test_gasto.py
> +            self.assertEqual(str(contexto.exception), f"El archivo {ruta_archivo} no existe")
Excepciones *en la lógica de negocio*. No se trata de escribir tests por escribirlos. Tratad de entender siempre el por qué.
En todo caso, ¿te parece que decir por qué la has hecho es relevante a la corrección o no? Entended los comentarios como sugerencias de mejora, no invitaciones a la discusión (que a lo mejor en época lectiva podían hacerse en clase, pero igual ya no es el momento)

2025-01-08 09:17 UTC, juanmaaf commented on money_controller/presupuesto.py
> +                raise ValueError("El archivo está vacío.")
Lo añadí por testear posibles excepciones, aunque consideraré que no tiene sentido.

2025-01-08 09:20 UTC, juanmaaf commented on test/test_gasto.py
> +        procesar_gasto(presupuesto, gastos_vistos, "Alquiler", "Vivienda", ALQUILER_IMPORTE, FECHA_ALQUILER)
En el test si trato de comprobar si el programa devuelve correctamente si son gastos fijos o variables. Pero en los atributos de entrada, nunca hablo de Gasto Fijo o Variable. De eso se encarga la lógica del programa. Y he aplicado la heurística de que se considerarán gastos fijos los recurrentes en el fichero de gastos. Variables serán el resto. Inicialmente, todo gasto se categoriza como Variable. Su clave (concepto, categoría, importe) se guarda en gastos_vistos. Cuando se procesa un gasto cuya clave está en este array, el programa lo categoriza como Fijo. Además, busca el primer gasto con la misma clave que se categorizó como Variable al no haber recurrencia. Así, coherentemente, todos los gastos con la misma clave serán Fijos.

2025-01-08 09:24 UTC, juanmaaf commented on test/test_gasto.py
> +    def test_leer_archivo_error(self):
Testear excepciones, como indica el guion. Pero consideraré eliminarlos si no añaden valor.

2025-01-08 09:27 UTC, juanmaaf commented on test/test_gasto.py
> +    def test_actualizar_monto_total(self):
Tiene razón. No añade valor. Creía que debía testear todo método que definiese. Error mío en la metodología. Aunque sea una operación de sumar, quería implementarlo por separado de los métodos que lo requieren.

2025-01-08 09:27 UTC, juanmaaf commented on test/test_gasto.py
> +    def test_leer_archivo_error(self):
Ya he visto su comentario. Solo se testea la lógica de negocio. Perdone las molestias.

2025-01-08 10:10 UTC, juanmaaf commented on money_controller/presupuesto.py
> +    meta_ahorro: float = None
Lo reharé. Disculpe las molestias

2025-01-08 16:52 UTC, juanmaaf commented on docs/test_runner.md
> +- Se considerará que la herramienta tenga un sistema de fixtures y proporcione salidas detalladas.
Resuelto en [228bfa8](https://github.com/juanmaaf/MoneyController/pull/17/commits/228bfa8f26e58611c50166fbe82d7fc9bd05780a)

2025-01-08 16:58 UTC, juanmaaf commented on money_controller/presupuesto.py
> +                raise ValueError("El archivo está vacío.")
Resuelto en [42e3f9c](https://github.com/juanmaaf/MoneyController/pull/17/commits/42e3f9cdf527d6c3bd9ba3d806622e9a68b24c12)

2025-01-08 17:01 UTC, juanmaaf commented on money_controller/presupuesto.py
> +    meta_ahorro: float = None
Volví al código del Objetivo 2 en el incorrecto issue para eliminarlo con el commit [9dbb5ee](https://github.com/juanmaaf/MoneyController/pull/17/commits/9dbb5ee465ede3c77ce51deb48ec8a7ee38edc67). Con los commit [c7f89af](https://github.com/juanmaaf/MoneyController/pull/17/commits/c7f89afd39db495f1a10bd439fb200840d7ad090) y [f9115c4](https://github.com/juanmaaf/MoneyController/pull/17/commits/f9115c44c6dac3c72851342777438535a0afde35) cierro el nuevo issue #25 creado de forma correcta formulando un problema.

2025-01-08 17:02 UTC, juanmaaf commented on test/test_gasto.py
> +    def test_leer_archivo_error(self):
Resuelto en [42e3f9c](https://github.com/juanmaaf/MoneyController/pull/17/commits/42e3f9cdf527d6c3bd9ba3d806622e9a68b24c12)

2025-01-08 17:06 UTC, juanmaaf commented on money_controller/gasto.py
> +    fecha: datetime
Añado esos campos para resolver el problema formulado en el issue #25. Resuelto en [c7f89af](https://github.com/juanmaaf/MoneyController/pull/17/commits/c7f89afd39db495f1a10bd439fb200840d7ad090)

2025-01-08 17:10 UTC, juanmaaf commented on money_controller/presupuesto.py
> +def procesar_datos(ruta_archivo):
Resuelto en [a964040](https://github.com/juanmaaf/MoneyController/pull/17/commits/a96404028de509bf3378331e63b1a75b34f0f048)

2025-01-08 17:38 UTC, juanmaaf commented on docs/gastos.csv
> +2024-01-01,Alquiler,Vivienda,226.67,Gasto
Finalmente, dado que no uso la categoría en el programa, he decidido no almacenarla. Resuelto en [35b5fb6](https://github.com/juanmaaf/MoneyController/pull/17/commits/35b5fb6647ac8876d74d611c24d33ecf65b586f1)

2025-01-08 18:40 UTC, juanmaaf commented
He tratado de resolver cada uno de los comentarios siguiendo las buenas prácticas, eliminado lo innecesario que no crea valor. Solicito revisión @JJ, por favor.

2025-01-09 07:02 UTC, JJ commented
> 
>     * [x]   ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
>       este objetivo?
> 

¿Qué producto es ese?
> 
>     * [x]  ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
>       delante?
> 

¿Cuál de los dos?

2025-01-09 07:08 UTC, JJ requested changes
[Aqui](https://github.com/juanmaaf/MoneyController/pull/17#discussion_r1891677110) también te hice un comentario sobre lo equivocado que era ese criterio. Te limitas a reescribirlo con frases rebuscadas como "Se considerará que la herramienta ofrezca métodos que implementen la lógica de la aserción". De veras que no creo que sea la mejor forma de invertir tu tiempo, ni por supuesto el de tus compañeros y el mío. Una vez más, no pasas ese objetivo en la convocatoria ordinaria ni voy a corregirlo ya más hasta que pase la fecha de la prueba.
Puedes empezar con el tres si quieres, aunque tampoco lo voy a corregir antes de esa fecha.

2025-01-09 07:08 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerará que la herramienta ofrezca métodos que implementen la lógica de la aserción, como los tipos (igualdad, veracidad, mayor/menor, etc.), aserciones específicas de excepciones, o enfoque
o sea, se valorará que una biblioteca de aserciones implemente aserciones.

2025-01-09 07:08 UTC, JJ commented on docs/biblioteca_aserciones.md
> +- Se considerará que la herramienta ofrezca una amplia gama de opciones para realizar diferentes tipos de aserciones.
Aquí hossam ya te hizo un comentario sobre lo que ahora dice " Se considerará que la herramienta ofrezca métodos que implementen la lógica de la aserción".
Yo te lo comenté más adelante también.

2025-01-09 08:46 UTC, juanmaaf commented
Ya sé que Hossam me comentó eso respecto a ese objetivo. Al final obtuve su apto tratando de resolver los errores que cometí. Y con sus comentarios, he tratado de formular el criterio de la forma más objetiva posible. Planteé ese criterio para diferenciar el Asserr Nativo de Python del resto de herramientas. Error mío al considerarlo, pues no es una biblioteca de aserciones. Lo eliminaré, como corresponde. Estoy tratando de trabajar sin hacer perder el tiempo a nadie. Disculpe las molestias. Para el objetivo 3, ¿creo un nuevo PR?

2025-01-09 09:09 UTC, juanmaaf commented
Respecto al comentario sobre la lista de comprobación, el producto mínimo viable es el definido en el Milestone 1, asignado a este objetivo. En él se menciona que se implementará un algoritmo que lea y procese los gastos además de uno que calcule que un gasto adicional es viable. He tratado de desacoplar todo lo máximo posible para que sean métodos simples. Alguno agrupa varios métodos, pues haría varias cosas si todo el código estuviese en el mismo método. Puedo considerar eliminar la parte del gasto adicional, para obtener un producto aún más mínimo. Sin embargo, ni resuelve el Milestone 1 ni el problema formulado en #4.

2025-01-13 19:32 UTC, juanmaaf commented
He realizado bastantes cambios desde que recibí vuestro apto. ¿Podríais revisarme de nuevo? Muchas gracias por vuestro tiempo y paciencia. @hossam1522 @antoniorr02 @juanbarearojo

2025-01-14 12:24 UTC, hossam1522 commented on docs/biblioteca_aserciones.md
> +- Se considerará si existe una biblioteca de aserciones en la biblioteca de Python.
Hmm se me hace extraño meter esto como criterio. ¿No crees que sería más válido decir algo como `intentar reducir las dependencias`?

2025-01-14 12:24 UTC, hossam1522 commented on test/test_gasto.py
> +        self.assertEqual(importe, 226.67)
Cuidado con los números mágicos.

2025-01-14 12:24 UTC, hossam1522 commented on test/test_gasto.py
> +from money_controller import presupuesto as p
Esto puede hacer algo menos entendible el código, ¿no crees?

2025-01-14 12:24 UTC, hossam1522 commented on docs/test_runner.md
> +Finalmente, entre todas las opciones elegiré **Pytest**. Descarto Unittest ya que a pesar de ser el framework estándar de pruebas no es un test runner. El test runner que incluye la herramienta es ba
Si no es un test runner, ¿por qué siquiera ha sido considerado?

2025-01-14 17:45 UTC, juanmaaf commented on docs/test_runner.md
> +Finalmente, entre todas las opciones elegiré **Pytest**. Descarto Unittest ya que a pesar de ser el framework estándar de pruebas no es un test runner. El test runner que incluye la herramienta es ba
Resuelto en [8d8bfad](https://github.com/juanmaaf/MoneyController/pull/17/commits/8d8bfadb439b10fda649f3d72c15c6e476b115c5)

2025-01-14 17:45 UTC, juanmaaf commented on test/test_gasto.py
> +from money_controller import presupuesto as p
Resuelto en [7316bfe](https://github.com/juanmaaf/MoneyController/pull/17/commits/7316bfec2e437ebd124e9689cc016d24469b0f7a)

2025-01-14 17:45 UTC, juanmaaf commented on test/test_gasto.py
> +        self.assertEqual(importe, 226.67)
Resuelto en [db12448](https://github.com/juanmaaf/MoneyController/pull/17/commits/db12448cc6f9b8da5e828db6035f31f3372aa374)

2025-01-14 17:45 UTC, juanmaaf commented on docs/biblioteca_aserciones.md
> +- Se considerará si existe una biblioteca de aserciones en la biblioteca de Python.
Resuelto en [cc43aed](https://github.com/juanmaaf/MoneyController/pull/17/commits/cc43aedfd77cf196e6dcefd2e4c09522ff5d087a)

2025-01-14 20:49 UTC, hossam1522 approved these changes
Realmente no se me ocurre mucho más que comentar, lo considero correcto.

2025-01-15 12:04 UTC, antoniorr02 reviewed
Buenas he revisado el objetivo y es de los mejor conseguidos que he visto por ahora, lo único a lo que le puedo sacar algo de pegas es que en algunas herramientas haces descripciones breves, lo cuál no aporta nada, ya que puede ser encontrado en los enlaces que proporcionas a dichas herramientas, con ese cambio tienes mi aprobado.

2025-01-15 12:04 UTC, antoniorr02 commented on docs/herramientas_cli.md
> +    Pytest es uno de los test runners más populares y usados en proyectos desarrollados en Python. Es una Herramienta CLI, ya que proporciona un comando para la ejecución de los tests. Además, ofrece
Es cierto que no describes mucho la herramienta, pero debes de ceñirte estrictamente a los criterios y no describir cosas de la herramienta, ya que esto se puede encontrar en la documentación de la misma, la cual ya estás enlazando.

2025-01-15 12:04 UTC, antoniorr02 commented on docs/herramientas_cli.md
> +    Nose2 es un framework de pruebas compatible con Unittest e incluye características que lo hacen más flexible y avanzado. Es una Herramienta CLI, ya que proporciona un comando para la ejecución de
Lo mismo

2025-01-15 12:04 UTC, antoniorr02 commented on docs/herramientas_cli.md
> +    Hammet es un test runner que, como podemos ver en su página de Snyk Advisor, indica que es mucho más rápido que Pytest, justificando la afirmación con comparacions detalladas. Es una Herramienta
Lo mismo

2025-01-15 12:04 UTC, antoniorr02 commented on docs/test_runner.md
> +    Pytest es uno de los test runners más populares y usados en proyectos desarrollados en Python. Ofrece soporte para fixtures y proporciona salidas detalladas. En su página de Snyk Advisor podemos
lo mismo

2025-01-15 12:53 UTC, juanmaaf commented on docs/test_runner.md
> +    Pytest es uno de los test runners más populares y usados en proyectos desarrollados en Python. Ofrece soporte para fixtures y proporciona salidas detalladas. En su página de Snyk Advisor podemos
Resuelto en [0ee0d8c](https://github.com/juanmaaf/MoneyController/pull/17/commits/0ee0d8c648f935f0c48c8b5af9554c90ffef8ad1)

2025-01-15 12:53 UTC, juanmaaf commented on docs/herramientas_cli.md
> +    Hammet es un test runner que, como podemos ver en su página de Snyk Advisor, indica que es mucho más rápido que Pytest, justificando la afirmación con comparacions detalladas. Es una Herramienta
Resuelto en [0ee0d8c](https://github.com/juanmaaf/MoneyController/pull/17/commits/0ee0d8c648f935f0c48c8b5af9554c90ffef8ad1)

2025-01-15 12:53 UTC, juanmaaf commented on docs/herramientas_cli.md
> +    Pytest es uno de los test runners más populares y usados en proyectos desarrollados en Python. Es una Herramienta CLI, ya que proporciona un comando para la ejecución de los tests. Además, ofrece
Resuelto en [0ee0d8c](https://github.com/juanmaaf/MoneyController/pull/17/commits/0ee0d8c648f935f0c48c8b5af9554c90ffef8ad1)

2025-01-15 12:55 UTC, juanmaaf commented
Muchas gracias por tus comentarios. He considerado lo que me has comentado y he dedicido eliminar el texto descriptivo de la herramienta, ya que como bien dices se puede ver qué es la herramienta en la documentación que adjunto. Revisión, por favor. @antoniorr02

2025-01-15 12:56 UTC, antoniorr02 approved these changes
Por mi parte considero el objetivo ampliamente superado. ¡Enhorabuena!

2025-01-15 13:50 UTC, juanmaaf commented
Muchas gracias por emplear vuestro tiempo en revisarme @hossam1522 @antoniorr02 . Me ha servido para poder entender bien la metodología que tanto se me ha complicado. He entendido mis errores y he tratado de resolverlos de la mejor forma posible. También me ha servido para poder ayudar a los demás en la superación de los objetivos, igual que vosotros me habéis ayudado a mí. Revisión, por favor @JJ .

2025-01-17 10:08 UTC, JJ requested changes
Tanto código en los tests se hace difícil de revisar. Un poco de DRY (don't repeat yourself) vendría bien, con un simple array o alguna estructura que contuviera entradas y salidas del test. Por otro lado, el problema principal es la situación del CSV, que entiendo que se usa solamente en tests. Además, hay uno solo; quizás los casos de test deberían ser más.

2025-01-17 21:56 UTC, juanmaaf commented on money_controller/presupuesto.py
> +    convertir_a_fijo(presupuesto, descripcion, monto)
Voy a considerar que solo se haga esta búsqueda la primera vez, ya que no tendría sentido hacer la búsqueda cuando el gasto variable con clave vista ya se ha actualizado.

2025-01-17 22:26 UTC, juanmaaf commented on docs/gastos.csv
Es más adecuado situarlo en el directorio tests. Resuelto en [a35ee2d](https://github.com/juanmaaf/MoneyController/pull/17/commits/a35ee2d9811d7933b0bb372854e49eb74fe647df)

2025-01-17 22:27 UTC, juanmaaf commented on money_controller/presupuesto.py
> +    convertir_a_fijo(presupuesto, descripcion, monto)
He tratado de explicar la lógica de negocio que he implementado en los docstrings y simplificado lo máximo posible para no marear. Es cierto que lo separo en métodos pero considero que desacoplando el método principal se puede entender por partes. Resuelto en: [7920491](https://github.com/juanmaaf/MoneyController/pull/17/commits/79204914c28ebe5617846dc0843b6e449e9a1640)

2025-01-17 22:35 UTC, juanmaaf commented
Respecto al problema que plantea el CSV, realmente en los test no uso el CSV. Tomo subpartes bastante simples que me permiten aplicar los algoritmos implementados y testearlos para ver el resultado. Añadí el CSV a este PR para que se comprendiese el formato de los datos de los que dispone el usuario. El único test que realmente emplea un CSV es el que prueba el método procesar_presupuesto. Pero empleo los mock que proporciona Unittest para simular este archivo en distintos escenarios (solo gastos recurrentes, gastos distintos, ingresos y gastos). Puede verse en los tres test: `test_procesar_presupuesto_...`. Aprovechando los mock de Unittest consideré que no es necesario crear nuevos archivos para testear. No obstante, consideraré su propuesta y si ha generado duda es que algo no estoy haciendo bien. Muchas gracias por su tiempo y revisión.

2025-01-17 23:10 UTC, juanmaaf commented
He considerado su propuesta en los test y he definido estructuras que incluyen la entrada y la salida esperada y decidido juntar los test que probaban el mismo método, estableciendo distintos casos. Esto me ha permitido reducir el número de tests de 11 a 5 y además eliminar mucho código, que además se repetía. Gracias por sus indicaciones.

2025-01-17 23:13 UTC, juanmaaf commented
Por último, creo que no es necesario que no es necesario crear nuevos CSV. Los comentarios se resuelven con commits y no por aquí, pero ese comentario no me lo ha hecho concretamente en ninguno de los archivos, por lo que considero que la presencia de los mocks en los test basta para justificar y resolver ese comentario. No obstante, estoy dispuesto a aceptar que lo que he hecho está mal y a trabajar en mejorarlo en ese caso. Como no tengo más que añadir en este objetivo, por ahora, solicito revisión, por favor. @JJ

2025-01-18 09:47 UTC, JJ commented
> Respecto al problema que plantea el CSV, realmente en los test no uso el CSV. Tomo subpartes bastante simples que me permiten aplicar los algoritmos implementados y testearlos para ver el resultado. Añadí el CSV a este PR para que se comprendiese el formato de los datos de los que dispone el usuario. El único test que realmente emplea un CSV es el que prueba el método procesar_presupuesto. Pero empleo los mock que proporciona Unittest para simular este archivo en distintos escenarios (solo gastos recurrentes, gastos distintos, ingresos y gastos). Puede verse en los tres test: `test_procesar_presupuesto_...`. Aprovechando los mock de Unittest consideré que no es necesario crear nuevos archivos para testear. No obstante, consideraré su propuesta y si ha generado duda es que algo no estoy haciendo bien. Muchas gracias por su tiempo y revisión.

En los tests es donde tienes que usar el CSV. No lo puedes usar en el código de producción, porque no forma parte de la lógica de negocio. Si lo estás usando en la lógica de negocio, estás planteando mal el programa.

2025-01-18 09:52 UTC, JJ requested changes
El fichero sigue estando donde estaba, pero aparte los cambios que has hecho han generado nuevos problemas. Ánimo, que ya queda poco.

2025-01-18 09:52 UTC, JJ commented on docs/gastos.csv
Lo has copiado, no lo has movido; por eso no se ha resuelto este comentario. Es mejor que uséis siempre `git mv` para que git sea capaz de trackear el cambio de directorio (en realidad, de nombre) sin perder los commits anteriores.

2025-01-18 09:52 UTC, JJ commented on money_controller/presupuesto.py
> +    if clave_gasto not in gasto_variable_convertido:
Estás agregando cosas al gasto variable en una función que se llama `agregar_gasto_fijo`. No sólo incumple el principio de responsabilidad única, es que además no describe lo que realmente hace.
Deberías intentar reorganizar el flujo de forma que sigas el principio de responsabilidad única para que sea más fácil entenderlo. Eso simplificará mucho el código. Trata de mirar *bien* la historia de usuario, ver cómo aparece cada gasto (inicialmente, siempre, de la forma más sencilla) y cómo averiguas si es variable o fijo.

2025-01-18 09:53 UTC, juanmaaf commented
No uso el CSV en la lógica de negocio, esa es mi intención y creo que el resultado del código implementado. Únicamente simulo archivos CSV en los test para simular datos de entrada, por eso comenté que no veía necesario crear nuevos CSV para los test, aunque siempre se pueden sustituir los mock por CSV reales.

2025-01-18 09:54 UTC, juanmaaf commented on money_controller/presupuesto.py
> +    if clave_gasto not in gasto_variable_convertido:
Lo tendré en cuenta.

2025-01-18 10:38 UTC, juanmaaf commented
He reflexionado su propuesta y creo que, analizando la HU que propone el problema del usuario, he planteado una solución que permite resolver el problema. Considero que no tiene sentido catalogar incialmente los gastos como fijos porque no sé en qué momento la lógica implementada podría considerarlos como variables. En caso contrario sí, incialmente VARIABLES y en cuanto sean recurrentes, todos los gastos con misma clave deberán ser fijos, incluido el primero que se registró, en su momento VARIABLE de forma correcta, pero debe actualizarse. No obstante, he tratado de reformular los métodos para reorganizar el flujo de forma que se siga el principio de responabilidad única. Por ello, he desacoplado lo que incluía en el método agregar_gasto_fijo y he definido un nuevo método convertir_gasto_variable_a_fijo que se ejecutará solamente en una situación determinada. Muchas gracias por su revisión, me ha permitido reflexionar aún más mi propio código y hacerlo más legible. Revisión, por favor. @JJ

2025-01-18 11:38 UTC, JJ approved these changes
Mira, voy a dar por aprobado porque al menos estás intentando mejorar el código, y además lo estás haciendo rápidamente. Sigue siendo código spaghetti, pero al menos ya no son a la boloñesa, con muchas cosas metidas por medio, sino un poco más carbonara, liados, pero más claritos.
Pero no hagas esto en tu trabajo, por favor.

2025-01-18 11:38 UTC, JJ commented on money_controller/presupuesto.py
> +    Se catalogará como gasto FIJO si es recurrente "visto".
Esto donde mejor iría es en el mensaje de commit. Es muy fácil acceder de un cambio al mensaje de commit; la documentación del método no tienes por qué tenerla presente o siquiera accesible.

2025-01-18 11:38 UTC, JJ commented on money_controller/presupuesto.py
> +        if clave_gasto not in gasto_variable_convertido:
Madre mía, la complejidad ciclomática...

2025-01-18 18:52 UTC, merged